"""Generate a Markdown function index for the src/ directory using Python ast.

Usage:
    uv run python tools/generate_functions_index.py
    uv run python tools/generate_functions_index.py --output docs/functions-index.md

The generated index is used by the Context Pack mechanism in build_review_context
to provide relevant function definitions to the AI model.
"""

from __future__ import annotations

import ast
import os
import argparse
from pathlib import Path


def extract_functions(filepath: str) -> list[dict[str, object]]:
    """Parse a Python file and extract function/class definitions using ast.

    Returns a list of dicts with keys:
        file_path, kind, name, args, returns, line, docstring
    """
    with open(filepath, "r", encoding="utf-8", errors="surrogateescape") as f:
        try:
            tree = ast.parse(f.read(), filename=filepath)
        except (SyntaxError, ValueError, TypeError):
            return []

    entries: list[dict[str, object]] = []

    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            args_str = ", ".join(
                arg.arg for arg in node.args.args
            )
            returns_str = (
                ast.unparse(node.returns) if node.returns else ""
            )
            doc = ast.get_docstring(node) or ""
            entries.append(
                {
                    "file_path": filepath,
                    "kind": "function",
                    "name": node.name,
                    "args": f"({args_str})",
                    "returns": returns_str,
                    "line": node.lineno,
                    "docstring": doc[:200] if doc else "",
                }
            )
        elif isinstance(node, ast.AsyncFunctionDef):
            args_str = ", ".join(
                arg.arg for arg in node.args.args
            )
            returns_str = (
                ast.unparse(node.returns) if node.returns else ""
            )
            doc = ast.get_docstring(node) or ""
            entries.append(
                {
                    "file_path": filepath,
                    "kind": "async_function",
                    "name": node.name,
                    "args": f"({args_str})",
                    "returns": returns_str,
                    "line": node.lineno,
                    "docstring": doc[:200] if doc else "",
                }
            )
        elif isinstance(node, ast.ClassDef):
            doc = ast.get_docstring(node) or ""
            entries.append(
                {
                    "file_path": filepath,
                    "kind": "class",
                    "name": node.name,
                    "args": "",
                    "returns": "",
                    "line": node.lineno,
                    "docstring": doc[:200] if doc else "",
                }
            )

    return entries


def generate_index(src_dir: str, output_path: str | None = None) -> str:
    """Scan src/ directory and generate a Markdown function index."""
    base = Path(src_dir).resolve()
    all_entries: list[dict[str, object]] = []

    for root, dirs, files in os.walk(src_dir):
        # Skip __pycache__ and .venv
        dirs[:] = [d for d in dirs if d not in ("__pycache__", ".venv", ".pytest_cache")]
        for f in files:
            if f.endswith(".py"):
                fpath = os.path.join(root, f)
                entries = extract_functions(fpath)
                all_entries.extend(entries)

    # Sort by file path then line number
    all_entries.sort(key=lambda e: (e["file_path"], e["line"]))  # type: ignore[arg-type]

    lines: list[str] = [
        "# Function Index",
        "",
        "Auto-generated by `tools/generate_functions_index.py`. Do not edit manually.",
        "",
        f"Total entries: {len(all_entries)}",
        "",
        "---",
        "",
    ]

    current_file = ""
    for entry in all_entries:
        filepath = entry["file_path"]
        relpath = os.path.relpath(filepath, str(base.parent))

        if filepath != current_file:
            current_file = filepath
            lines.append(f"## `{relpath}`")
            lines.append("")

        kind = entry["kind"]
        name = entry["name"]
        args = entry["args"]
        returns = entry["returns"]
        line = entry["line"]
        doc = entry["docstring"]

        sig = f"`{name}{args}`"
        if returns:
            sig += f" → `{returns}`"

        if kind == "class":
            lines.append(f"- **class** {sig}  _(line {line})_")
        elif kind == "async_function":
            lines.append(f"- **async def** {sig}  _(line {line})_")
        else:
            lines.append(f"- **def** {sig}  _(line {line})_")

        if doc:
            # Take only first line for compactness
            first_line = doc.split("\n")[0].strip()
            if first_line:
                lines.append(f"  - {first_line}")

        lines.append("")

    result = "\n".join(lines)

    if output_path:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(result)
        print(f"Index written to {output_path} ({len(all_entries)} entries)")

    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate function index for src/")
    parser.add_argument(
        "--output", "-o",
        default="docs/functions-index.md",
        help="Output Markdown file path (default: docs/functions-index.md)",
    )
    parser.add_argument(
        "--src",
        default="src",
        help="Source directory to scan (default: src)",
    )
    args = parser.parse_args()

    # Resolve paths relative to project root
    project_root = Path(__file__).resolve().parent.parent
    src_dir = str(project_root / args.src)
    output_path = str(project_root / args.output)

    generate_index(src_dir, output_path)
